<?php
// $Id: xoops_version.php,v 1.2 2004/06/10 20:19:18 eric_juden Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
$modversion['name'] = _MI_SSTATUS_NAME;
$modversion['version'] = 1.1;
$modversion['description'] = _MI_SSTATUS_DESC;
$modversion['credits'] = "Brian Wahoff";    // Cool guys
$modversion['author'] = "Eric Juden";
$modversion['help'] = "not yet";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/sstatus_slogo.png";
$modversion['dirname'] = "sstatus";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "sstatus_services";
$modversion['tables'][1] = "sstatus_memos";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][1]['file'] = 'sstatus_index.html';
$modversion['templates'][1]['description'] = _MI_SSTATUS_TEMP_INDEX;
$modversion['templates'][2]['file'] = 'sstatus_service.html';
$modversion['templates'][2]['description'] = _MI_SSTATUS_TEMP_SERVICE;
$modversion['templates'][3]['file'] = 'sstatus_add.html';
$modversion['templates'][3]['description'] = _MI_SSTATUS_TEMP_ADD;
$modversion['templates'][4]['file'] = 'sstatus_edit.html';
$modversion['templates'][4]['description'] = _MI_SSTATUS_TEMP_EDIT;
$modversion['templates'][5]['file'] = 'sstatus_memo.html';
$modversion['templates'][5]['description'] = _MI_SSTATUS_TEMP_MEMO;
$modversion['templates'][6]['file'] = 'sstatus_modifyMemo.html';
$modversion['templates'][6]['description'] = _MI_SSTATUS_TEMP_MODIFYMEMO;

// Blocks
// Overview block that displays current services
$modversion['blocks'][1]['file'] = "sstatus_blocks.php";
$modversion['blocks'][1]['name'] = _MI_SSTATUS_BNAME1;
$modversion['blocks'][1]['description'] = _MI_SSTATUS_BNAME1_DESC;
$modversion['blocks'][1]['show_func'] = "b_sstatus_overview_show";
$modversion['blocks'][1]['template'] = 'sstatus_block_overview.html';

// Block that displays links to different pages
$modversion['blocks'][2]['file'] = "sstatus_blocks.php";
$modversion['blocks'][2]['name'] = _MI_SSTATUS_BNAME2;
$modversion['blocks'][2]['description'] = _MI_SSTATUS_BNAME2_DESC;
$modversion['blocks'][2]['show_func'] = "b_sstatus_admin_show";
$modversion['blocks'][2]['template'] = 'sstatus_block_admin.html';

// Menu
$modversion['hasMain'] = 1;
	
// Search
$modversion['hasSearch'] = 0;

// Config -- for Admin Menu->Preferences
/*
$modversion['config'][1]['name'] = 'pagenav_min';
$modversion['config'][1]['title'] = '_MI_PAGENAV_MIN';
$modversion['config'][1]['description'] = '_MI_PAGENAV_MINDSC';
$modversion['config'][1]['formtype'] = 'select';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 40;
$modversion['config'][1]['options'] = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '35' => 35, '40' => 40);
*/
$modversion['config'][2]['name'] = 'pagenav_max';
$modversion['config'][2]['title'] = '_MI_PAGENAV_MAX';
$modversion['config'][2]['description'] = '_MI_PAGENAV_MAXDSC';
$modversion['config'][2]['formtype'] = 'select';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 10;
$modversion['config'][2]['options'] = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '35' => 35, '40' => 40);

/*
$modversion['config'][3]['name'] = 'pagenav_default';
$modversion['config'][3]['title'] = '_MI_PAGENAV_DEFAULT';
$modversion['config'][3]['description'] = '_MI_PAGENAV_DEFAULTDSC';
$modversion['config'][3]['formtype'] = 'select';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 0;
$modversion['config'][3]['options'] = array('0' => 0, '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '35' => 35, '40' => 40);
*/

// Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'sstatus_notify_iteminfo';

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_SSTATUS_GLOBAL_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_SSTATUS_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array('index.php', 'service.php');

$modversion['notification']['category'][2]['name'] = 'service';
$modversion['notification']['category'][2]['title'] = _MI_SSTATUS_SERVICE_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_SSTATUS_SERVICE_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = array('service.php');
$modversion['notification']['category'][2]['item_name'] = 'id';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name'] = 'new_service';        // Add service
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['admin_only'] = 0;
$modversion['notification']['event'][1]['title'] = _MI_SSTATUS_GLOBAL_NEWSERVICE_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_SSTATUS_GLOBAL_NEWSERVICE_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_SSTATUS_GLOBAL_NEWSERVICE_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_newservice_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_SSTATUS_GLOBAL_NEWSERVICE_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'modified_service';   // Edit service information
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['admin_only'] = 0;
$modversion['notification']['event'][2]['title'] = _MI_SSTATUS_GLOBAL_MODIFIEDSERVICE_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_SSTATUS_GLOBAL_MODIFIEDSERVICE_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_SSTATUS_GLOBAL_MODIFIEDSERVICE_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_modifiedservice_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_SSTATUS_GLOBAL_MODIFIEDSERVICE_NOTIFYSBJ;

$modversion['notification']['event'][3]['name'] = 'removed_service';    // Delete service
$modversion['notification']['event'][3]['category'] = 'global';
$modversion['notification']['event'][3]['admin_only'] = 0;
$modversion['notification']['event'][3]['title'] = _MI_SSTATUS_GLOBAL_REMOVEDSERVICE_NOTIFY;
$modversion['notification']['event'][3]['caption'] = _MI_SSTATUS_GLOBAL_REMOVEDSERVICE_NOTIFYCAP;
$modversion['notification']['event'][3]['description'] = _MI_SSTATUS_GLOBAL_REMOVEDSERVICE_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template'] = 'global_removedservice_notify';
$modversion['notification']['event'][3]['mail_subject'] = _MI_SSTATUS_GLOBAL_REMOVEDSERVICE_NOTIFYSBJ;

$modversion['notification']['event'][4]['name'] = 'changed_status';     // Update status -- Add memo
$modversion['notification']['event'][4]['category'] = 'global';         // All services
$modversion['notification']['event'][4]['title'] = _MI_SSTATUS_GLOBAL_CHANGEDSTATUS_NOTIFY;
$modversion['notification']['event'][4]['caption'] = _MI_SSTATUS_GLOBAL_CHANGEDSTATUS_NOTIFYCAP;
$modversion['notification']['event'][4]['description'] = _MI_SSTATUS_GLOBAL_CHANGEDSTATUS_NOTIFYDSC;
$modversion['notification']['event'][4]['mail_template'] = 'global_changedstatus_notify';
$modversion['notification']['event'][4]['mail_subject'] = _MI_SSTATUS_GLOBAL_CHANGEDSTATUS_NOTIFYSBJ;

$modversion['notification']['event'][5]['name'] = 'modified_this_service';   // Edit service information
$modversion['notification']['event'][5]['category'] = 'service';        // Individual service
$modversion['notification']['event'][5]['admin_only'] = 0;
$modversion['notification']['event'][5]['title'] = _MI_SSTATUS_SERVICE_MODIFIEDSERVICE_NOTIFY;
$modversion['notification']['event'][5]['caption'] = _MI_SSTATUS_SERVICE_MODIFIEDSERVICE_NOTIFYCAP;
$modversion['notification']['event'][5]['description'] = _MI_SSTATUS_SERVICE_MODIFIEDSERVICE_NOTIFYDSC;
$modversion['notification']['event'][5]['mail_template'] = 'service_modifiedservice_notify';
$modversion['notification']['event'][5]['mail_subject'] = _MI_SSTATUS_SERVICE_MODIFIEDSERVICE_NOTIFYSBJ;

$modversion['notification']['event'][6]['name'] = 'removed_this_service';    // Delete service
$modversion['notification']['event'][6]['category'] = 'service';        // Individual service
$modversion['notification']['event'][6]['admin_only'] = 0;
$modversion['notification']['event'][6]['title'] = _MI_SSTATUS_SERVICE_REMOVEDSERVICE_NOTIFY;
$modversion['notification']['event'][6]['caption'] = _MI_SSTATUS_SERVICE_REMOVEDSERVICE_NOTIFYCAP;
$modversion['notification']['event'][6]['description'] = _MI_SSTATUS_SERVICE_REMOVEDSERVICE_NOTIFYDSC;
$modversion['notification']['event'][6]['mail_template'] = 'service_removedservice_notify';
$modversion['notification']['event'][6]['mail_subject'] = _MI_SSTATUS_SERVICE_REMOVEDSERVICE_NOTIFYSBJ;

$modversion['notification']['event'][7]['name'] = 'changed_this_service_status';     // Update status -- Add memo 
$modversion['notification']['event'][7]['category'] = 'service';                // Individual service
$modversion['notification']['event'][7]['title'] = _MI_SSTATUS_SERVICE_CHANGEDSTATUS_NOTIFY;
$modversion['notification']['event'][7]['caption'] = _MI_SSTATUS_SERVICE_CHANGEDSTATUS_NOTIFYCAP;
$modversion['notification']['event'][7]['description'] = _MI_SSTATUS_SERVICE_CHANGEDSTATUS_NOTIFYDSC;
$modversion['notification']['event'][7]['mail_template'] = 'service_changedstatus_notify';
$modversion['notification']['event'][7]['mail_subject'] = _MI_SSTATUS_SERVICE_CHANGEDSTATUS_NOTIFYSBJ;

$modversion['notification']['event'][8]['name'] = 'modified_service_status';   // Edit service information
$modversion['notification']['event'][8]['category'] = 'global';
$modversion['notification']['event'][8]['admin_only'] = 1;
$modversion['notification']['event'][8]['title'] = _MI_SSTATUS_GLOBAL_MODIFIEDSERVICE_STATUS_NOTIFY;
$modversion['notification']['event'][8]['caption'] = _MI_SSTATUS_GLOBAL_MODIFIEDSERVICE_STATUS_NOTIFYCAP;
$modversion['notification']['event'][8]['description'] = _MI_SSTATUS_GLOBAL_MODIFIEDSERVICE_STATUS_NOTIFYDSC;
$modversion['notification']['event'][8]['mail_template'] = 'global_modifiedservice_status_notify';
$modversion['notification']['event'][8]['mail_subject'] = _MI_SSTATUS_GLOBAL_MODIFIEDSERVICE_STATUS_NOTIFYSBJ;

$modversion['notification']['event'][9]['name'] = 'modified_this_service_status';   // Edit service information
$modversion['notification']['event'][9]['category'] = 'service';
$modversion['notification']['event'][9]['admin_only'] = 1;
$modversion['notification']['event'][9]['title'] = _MI_SSTATUS_SERVICE_MODIFIEDSERVICE_STATUS_NOTIFY;
$modversion['notification']['event'][9]['caption'] = _MI_SSTATUS_SERVICE_MODIFIEDSERVICE_STATUS_NOTIFYCAP;
$modversion['notification']['event'][9]['description'] = _MI_SSTATUS_SERVICE_MODIFIEDSERVICE_STATUS_NOTIFYDSC;
$modversion['notification']['event'][9]['mail_template'] = 'service_modifiedservice_status_notify';
$modversion['notification']['event'][9]['mail_subject'] = _MI_SSTATUS_SERVICE_MODIFIEDSERVICE_STATUS_NOTIFYSBJ;
?>